In [16]:
import numpy as np
a = np.arange(7,dtype=float)
print(a,type(a))
print('dim of a = ',a.ndim)
print('shape of a = ',a.shape)
print('size of a = ',a.size)
print('dtype of a = ',a.dtype)

[0. 1. 2. 3. 4. 5. 6.] <class 'numpy.ndarray'>
dim of a =  1
shape of a =  (7,)
size of a =  7
dtype of a =  float64


In [4]:
b = np.arange(1,10)
print(b,type(b))
print('dim of a = ',b.ndim)
print('shape of a = ',b.shape)
print('size of a = ',b.size)
print('dtype of a = ',b.dtype)

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
dim of a =  1
shape of a =  (9,)
size of a =  9
dtype of a =  int32


In [5]:
c = np.arange(1,10,3)
print(c,type(c))
print('dim of a = ',c.ndim)
print('shape of a = ',c.shape)
print('size of a = ',c.size)
print('dtype of a = ',c.dtype)

[1 4 7] <class 'numpy.ndarray'>
dim of a =  1
shape of a =  (3,)
size of a =  3
dtype of a =  int32


In [7]:
d = np.arange(10,1,-2)
print(d,type(d))
print('dim of a = ',d.ndim)
print('shape of a = ',d.shape)
print('size of a = ',d.size)
print('dtype of a = ',d.dtype)

[10  8  6  4  2] <class 'numpy.ndarray'>
dim of a =  1
shape of a =  (5,)
size of a =  5
dtype of a =  int32


In [14]:
e = np.arange(2*3*3).reshape(2,3,3)
print(e,type(e))
print('dim of a = ',e.ndim)
print('shape of a = ',e.shape)
print('size of a = ',e.size)
print('dtype of a = ',e.dtype)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]] <class 'numpy.ndarray'>
dim of a =  3
shape of a =  (2, 3, 3)
size of a =  18
dtype of a =  int32


In [15]:
f = np.arange(18).reshape(2,3,3)
print(f,type(f))
print('dim of a = ',f.ndim)
print('shape of a = ',f.shape)
print('size of a = ',f.size)
print('dtype of a = ',f.dtype)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]] <class 'numpy.ndarray'>
dim of a =  3
shape of a =  (2, 3, 3)
size of a =  18
dtype of a =  int32
