In [2]:
a = 4
print(a,type(a))

4 <class 'int'>


In [4]:
import numpy as np
nda = np.array(a,dtype=bool)
print(nda,type(nda))

True <class 'numpy.ndarray'>


In [6]:
print('dimention of array = ',nda.ndim)
print('shape of array = ',nda.shape)
print('size of array = ',nda.size)
print('type of array = ',nda.dtype)

dimention of array =  0
shape of array =  ()
size of array =  1
type of array =  bool


In [7]:
a = 'hii how are you'
print(a,type(a))

hii how are you <class 'str'>


In [9]:
nda = np.array(a,dtype=object)
print(nda,type(nda))

hii how are you <class 'numpy.ndarray'>


In [11]:
nda = np.array(a,dtype=object)
print(nda,type(nda))
print('dimention of array = ',nda.ndim)
print('shape of array = ',nda.shape)
print('size of array = ',nda.size)
print('type of array = ',nda.dtype)

hii how are you <class 'numpy.ndarray'>
dimention of array =  0
shape of array =  ()
size of array =  1
type of array =  object


In [12]:
a = range(1,10)
print(a,type(a))
print('-'*50)
nda = np.array(a,dtype=object)
print(nda,type(nda))
print('dimention of array = ',nda.ndim)
print('shape of array = ',nda.shape)
print('size of array = ',nda.size)
print('type of array = ',nda.dtype)

range(1, 10) <class 'range'>
--------------------------------------------------
[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
dimention of array =  1
shape of array =  (9,)
size of array =  9
type of array =  object


In [13]:
nda.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=object)

In [15]:
nda.shape=(9,)
nda

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=object)

In [17]:
nda.shape=(3,3)
print(nda)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
