In [1]:
import numpy as np
a = np.eye(3)
print(a,type(a))
print('dtype of a = ',a.dtype)
print('shape of a = ',a.shape)
print('size of a = ',a.size)
print('dim of a = ',a.ndim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'>
dtype of a =  float64
shape of a =  (3, 3)
size of a =  9
dim of a =  2


In [3]:
a = np.eye(3,k=1)
print(a,type(a))

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]] <class 'numpy.ndarray'>


In [5]:
b = np.eye(6,k=-3,dtype=int)
print(b,type(b))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]] <class 'numpy.ndarray'>


In [6]:
c = np.eye(3,4,k=1)
print(c,type(c))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] <class 'numpy.ndarray'>
