In [1]:
import numpy as np
a = np.full(6,4)
print(a,type(a))
print('dtype of a =',a.dtype)
print('shape of a =',a.shape)
print('dim of a =',a.ndim)
print('size of a =',a.size)

[4 4 4 4 4 4] <class 'numpy.ndarray'>
dtype of a = int32
shape of a = (6,)
dim of a = 1
size of a = 6


In [2]:
b = np.full((3,3),6)
print(b,type(b))
print('dtype of a =',b.dtype)
print('shape of a =',b.shape)
print('dim of a =',b.ndim)
print('size of a =',b.size)

[[6 6 6]
 [6 6 6]
 [6 6 6]] <class 'numpy.ndarray'>
dtype of a = int32
shape of a = (3, 3)
dim of a = 2
size of a = 9


In [3]:
c = np.full((2,3,3),8)
print(c,type(c))
print('dtype of a =',c.dtype)
print('shape of a =',c.shape)
print('dim of a =',c.ndim)
print('size of a =',c.size)

[[[8 8 8]
  [8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]
  [8 8 8]]] <class 'numpy.ndarray'>
dtype of a = int32
shape of a = (2, 3, 3)
dim of a = 3
size of a = 18
