In [9]:
import numpy as np
a = np.array([[1,2,3],[8,3,5]])
b = np.array([[3,21,1],[8,3,5]])
print(a,b)

[[1 2 3]
 [8 3 5]] [[ 3 21  1]
 [ 8  3  5]]


In [11]:
c = np.hstack((a,b))
print(c)

[[ 1  2  3  3 21  1]
 [ 8  3  5  8  3  5]]


In [17]:
a = np.arange(3*3).reshape(3,3)
b = np.arange(5,14).reshape(3,3)
print(a)
print(b)
c = np.hstack([a,b)]) # () must give
print('-'*50)
print(c)

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (356495446.py, line 5)

In [16]:
a = np.arange(4*3).reshape(4,3)
b = np.arange(3*4).reshape(3,4)
print(a)
print(b)
c = np.hstack((a,b))  # rows must be same
print('-'*50)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 3