In [2]:
import numpy as np
a = np.identity(3)
print(a,type(a))
print('dtype of a = ',a.dtype)
print('shape of a = ',a.shape)
print('size of a = ',a.size)
print('dim of a = ',a.ndim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'>
dtype of a =  float64
shape of a =  (3, 3)
size of a =  9
dim of a =  2


In [5]:
b = np.identity(2,dtype=int)
print(b,type(b))
print('dtype of a = ',b.dtype)
print('shape of a = ',b.shape)
print('size of a = ',b.size)
print('dim of a = ',b.ndim)

[[1 0]
 [0 1]] <class 'numpy.ndarray'>
dtype of a =  int32
shape of a =  (2, 2)
size of a =  4
dim of a =  2


In [10]:
c = np.identity(1)
print(c,type(c))
print('dtype of a = ',c.dtype)
print('shape of a = ',c.shape)
print('size of a = ',c.size)
print('dim of a = ',c.ndim)

[[1.]] <class 'numpy.ndarray'>
dtype of a =  float64
shape of a =  (1, 1)
size of a =  1
dim of a =  2


In [13]:
d = np.identity(2,dtype=int)
print(d,type(d))

TypeError: identity() got an unexpected keyword argument 'm'