In [5]:
import numpy as np
a = np.linspace(1,20,num = 20,endpoint=True,retstep=True,dtype=float)
print(a,type(a))
print('dtype of a = ',a.dtype)
print('dim of a = ',a.ndim)
print('size of a = ',a.size)
print('shape of a = ',a.shape)

(array([ 1.        ,  2.26315789,  3.52631579,  4.78947368,  6.05263158,
        7.31578947,  8.57894737,  9.84210526, 11.10526316, 12.36842105,
       13.63157895, 14.89473684, 16.15789474, 17.42105263, 18.68421053,
       19.94736842, 21.21052632, 22.47368421, 23.73684211, 25.        ]), 1.263157894736842) <class 'tuple'>


AttributeError: 'tuple' object has no attribute 'ndim'

In [7]:
b = np.linspace(start=1,stop=5,num=10,endpoint=True,retstep=True)
print(b)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]), 0.4444444444444444)


In [8]:
c = np.linspace(1,5,num=10,endpoint=False,retstep=False)
print(c,type(c))

[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6] <class 'numpy.ndarray'>


In [15]:
d = np.linspace(1,5,num=10,endpoint=False,retstep=True)
print(d,type(d))

(array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6]), 0.4) <class 'tuple'>


In [11]:
e = np.linspace(1,5,num=10)
print(e,type(e))

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ] <class 'numpy.ndarray'>


In [12]:
f = np.linspace(1,5)
print(f,type(f))

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ] <class 'numpy.ndarray'>


In [13]:
z = f.reshape(10,5)
print(z)

[[1.         1.08163265 1.16326531 1.24489796 1.32653061]
 [1.40816327 1.48979592 1.57142857 1.65306122 1.73469388]
 [1.81632653 1.89795918 1.97959184 2.06122449 2.14285714]
 [2.2244898  2.30612245 2.3877551  2.46938776 2.55102041]
 [2.63265306 2.71428571 2.79591837 2.87755102 2.95918367]
 [3.04081633 3.12244898 3.20408163 3.28571429 3.36734694]
 [3.44897959 3.53061224 3.6122449  3.69387755 3.7755102 ]
 [3.85714286 3.93877551 4.02040816 4.10204082 4.18367347]
 [4.26530612 4.34693878 4.42857143 4.51020408 4.59183673]
 [4.67346939 4.75510204 4.83673469 4.91836735 5.        ]]


In [19]:
y = np.array(d).reshape(2,5)
print(y,type(y))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.