In [1]:
import numpy as np
a = np.ones(3)
print(a,type(a))
print('dim of a = ',a.ndim)
print('shape of a = ',a.shape)
print('size of a = ',a.size)
print('dtype of a = ',a.dtype)

[1. 1. 1.] <class 'numpy.ndarray'>
dim of a =  1
shape of a =  (3,)
size of a =  3
dtype of a =  float64


In [2]:
b = np.ones((3,3),dtype = int)
print(b,type(b))
print('dim of a = ',b.ndim)
print('shape of a = ',b.shape)
print('size of a = ',b.size)
print('dtype of a = ',b.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]] <class 'numpy.ndarray'>
dim of a =  2
shape of a =  (3, 3)
size of a =  9
dtype of a =  int32


In [4]:
c = np.ones((2,3,3),dtype = str)
print(c,type(c))
print('dim of a = ',c.ndim)
print('shape of a = ',c.shape)
print('size of a = ',c.size)
print('dtype of a = ',c.dtype)

[[['1' '1' '1']
  ['1' '1' '1']
  ['1' '1' '1']]

 [['1' '1' '1']
  ['1' '1' '1']
  ['1' '1' '1']]] <class 'numpy.ndarray'>
dim of a =  3
shape of a =  (2, 3, 3)
size of a =  18
dtype of a =  <U1
