In [4]:
import  numpy as np
a = np.array([[1,2,3,4],[45,5,6,7]])
print(a)
b = np.array([[4,5,6],[5,6,7]])
print(b)
c = np.hstack((a,b)) # rows are same
print(c)
d = np.vstack((a,b)) # columns are not same
print(d)

[[ 1  2  3  4]
 [45  5  6  7]]
[[4 5 6]
 [5 6 7]]
[[ 1  2  3  4  4  5  6]
 [45  5  6  7  5  6  7]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

In [10]:
e = np.array([[1,2,3,4],[45,5,6,7]])
print(e)
f = np.array([[4,5,6,8],[5,6,7,9],[23,45,36,7]])
print(f)
h = np.vstack((e,f)) # coloumns are same
print('-'*50)
print(h)
g = np.hstack((e,f))  # rows are not same
print(g)

[[ 1  2  3  4]
 [45  5  6  7]]
[[ 4  5  6  8]
 [ 5  6  7  9]
 [23 45 36  7]]
--------------------------------------------------
[[ 1  2  3  4]
 [45  5  6  7]
 [ 4  5  6  8]
 [ 5  6  7  9]
 [23 45 36  7]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3