In [2]:
# a = numpy.zeros(shape,dtype)
import numpy as np
a = np.zeros(3)
print(a,type(a))
print('dim of a = ',a.ndim)
print('shape of a = ',a.shape)
print('size of a = ',a.size)
print('dtype of a = ',a.dtype)

[0. 0. 0.] <class 'numpy.ndarray'>
dim of a =  1
shape of a =  (3,)
size of a =  3
dtype of a =  float64


In [9]:
b = np.zeros((2,2),dtype=int)
print(b,type(b))
print('dim of a = ',b.ndim)
print('shape of a = ',b.shape)
print('size of a = ',b.size)
print('dtype of a = ',b.dtype)

[[0 0]
 [0 0]] <class 'numpy.ndarray'>
dim of a =  2
shape of a =  (2, 2)
size of a =  4
dtype of a =  int32


In [7]:
c = np.zeros((2,3,3),int)
print(c,type(c))
print('dim of a = ',c.ndim)
print('shape of a = ',c.shape)
print('size of a = ',c.size)
print('dtype of a = ',c.dtype)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]] <class 'numpy.ndarray'>
dim of a =  3
shape of a =  (2, 3, 3)
size of a =  18
dtype of a =  int32
